### ISSUE TITLE
Can't build locally

### ISSUE THREAD

**Issue by HunteRoi** [smakosh/next-portfolio-dev#10]
I've been trying to locally build the app but it seems like I fall on a 401 (only when running `yarn build` - it works fine with `yarn dev`).

```
PS C:\git\hunteroi.github.io> yarn dev   
yarn run v1.22.10
$ next dev -p 3040
ready - started server on 0.0.0.0:3040, url: http://localhost:3040
info  - Loaded env from C:\git\hunteroi.github.io\.env.development.local
info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
info  - Using external babel configuration from C:\git\hunteroi.github.io\.babelrc
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully

PS C:\git\hunteroi.github.io> yarn build
yarn run v1.22.10
$ next build
info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully 
info  - Collecting page data  
[   =] info  - Generating static pages (0/3)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Request failed with status code 401
    at createError (C:\git\hunteroi.github.io\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\git\hunteroi.github.io\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\git\hunteroi.github.io\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
        /
    at C:\git\hunteroi.github.io\node_modules\next\dist\export\index.js:31:1106
    at async Span.traceAsyncFn (C:\git\hunteroi.github.io\node_modules\next\dist\telemetry\trace\trace.js:6:584)
    at async C:\git\hunteroi.github.io\node_modules\next\dist\build\index.js:43:49
    at async Span.traceAsyncFn (C:\git\hunteroi.github.io\node_modules\next\dist\telemetry\trace\trace.js:6:584)
    at async C:\git\hunteroi.github.io\node_modules\next\dist\build\index.js:25:1475
    at async Span.traceAsyncFn (C:\git\hunteroi.github.io\node_modules\next\dist\telemetry\trace\trace.js:6:584)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've edited a bit the code to fit my template, you can check if the problem comes from the source code itself : https://github.com/hunteroi/hunteroi.github.io but I highly doubt about this.

Any idea? Thanks for any further response!

**Comment by smakosh** [comment]
Will check that today

**Comment by smakosh** [comment]
Hey @HunteRoi, you will simply need to create a `.env.production.local` file for Next js to recognize your production env variables, I have updated the docs here to highlight this: https://github.com/smakosh/next-portfolio-dev/pull/11

Thanks for reporting the issue!
